### ISSUE TITLE
Add your Details to user.js and join hacktoberfest-2020 with another PR

### ISSUE THREAD

**Issue by MasterBrian99** [MasterBrian99/Hacktoberfest-2k20#2]
# Read Readme.md file and get more information.mainly focused beginners.but everyone can contribute..

**Comment by rzadev** [comment]
@MasterBrian99 I have created a pull request, please review it.

**Comment by SriCoD** [comment]
im passionate to work on this, could i be given a chance

**Comment by MasterBrian99** [comment]
> im passionate to work on this, could i be given a chance

go ahead.Read information first.good luck !

**Comment by irvine09** [comment]
@MasterBrian99 added my info. please review too. thanks in advance.

**Comment by SriCoD** [comment]
I'm working on it
